[theme]
primaryColor = "#50586C"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f5"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false

[ui]
hideStreamlitMark = true